import fs from 'node:fs';
import path from 'node:path';
import {sectors,variants} from '../src/sectors.mjs';
import {posts} from '../src/posts.mjs';
import {byId,verticals} from '../src/verticals.mjs';
import {renderDemo} from '../src/experience.mjs';
const root=path.resolve('dist');fs.rmSync(root,{recursive:true,force:true});fs.mkdirSync(root,{recursive:true});
fs.cpSync('assets',root+'/assets',{recursive:true});fs.copyFileSync('src/style.css',root+'/assets/style.css');fs.copyFileSync('src/client.js',root+'/assets/client.js');
fs.copyFileSync('src/experience.css',root+'/assets/experience.css');fs.copyFileSync('src/experience.js',root+'/assets/experience.js');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pages=[];
function write(route,html){const file=path.join(root,route,'index.html');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,html);pages.push('/'+(route?route+'/':''));}
function shell(title,description,content,cls='',extra=''){return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(description)}"><meta name="theme-color" content="${cls==='moto'?'#222b25':'#192c32'}"><title>${esc(title)}</title><link rel="icon" ${cls==='moto'?'type="image/webp" href="/assets/motoyayos-icon.webp"':'type="image/svg+xml" href="/assets/favicon.svg"'}><link rel="stylesheet" href="/assets/style.css"><script defer src="/assets/client.js"></script>${extra}</head><body class="${cls}"><a class="skip" href="#main">Saltar al contenido</a>${content}</body></html>`;}
const photo=(i,label,cls='')=>`<div class="photo ${cls}" role="img" aria-label="${esc(label)}" style="--photo-url:url('/assets/sector-${i}.webp');--photo-x:${i%3*50}%;--photo-y:${Math.floor(i/3)*50}%"></div>`;
const btn=(label,url,cls='')=>`<a class="btn ${cls}" href="${url}">${esc(label)}</a>`;
const footer=()=>`<footer class="site-footer wrap"><span>Estudio Web · Un escaparate de posibilidades.</span><span>Marcas, contenidos e imágenes de demostración.</span><a href="/">Volver al catálogo</a></footer>`;
const hubnav=()=>`<header class="topbar"><nav class="nav wrap" aria-label="Navegación principal"><a class="wordmark" href="/"><span class="mark" aria-hidden="true">e.</span>estudio web</a><div class="navlinks"><a href="/#catalogo">Explorar diseños</a><a href="/motoyayos/">Motoyayos</a><a class="optional" href="/#especial">Proyecto especial</a></div></nav></header>`;
const card=s=>`<article class="sector-card" data-sector="${s.id}" data-category="${esc(s.category)}" data-ticket="${s.highTicket}" data-search="${esc(s.name+' '+s.category+' '+s.services.join(' '))}"><a href="/sectores/${s.id}/" aria-label="Comparar los tres diseños de ${esc(s.name)}">${photo(s.photo,s.name)}</a><div class="card-info"><div><span class="category">${esc(s.category)}</span><h3><a href="/sectores/${s.id}/">${esc(s.name)}</a></h3></div>${s.highTicket?'<span class="ticket">Ticket alto</span>':''}</div><div class="versions" aria-label="Versiones de ${esc(s.name)}">${byId[s.id].versions.map(v=>`<a href="/demos/${s.id}/${v.id}/"><span>${v.id.toString().padStart(2,'0')}</span> ${v.name}</a>`).join('')}</div></article>`;
const categories=[...new Set(sectors.map(s=>s.category))];
write('',shell('Estudio Web · Encuentra la web de tu negocio','45 gremios, 135 diseños y el blog Motoyayos. Explora tres propuestas para cada tipo de negocio.',`${hubnav()}<main id="main" class="wrap"><section class="intro"><div><span class="eyebrow">Un negocio. Tres maneras de contarlo.</span><h1>Tu próxima web<br>empieza con <em>una idea.</em></h1></div><div><p>Explora negocios que funcionan: elige un coche, reserva una cita, configura un proyecto o prepara un pedido. Tres experiencias por gremio.</p><div class="facts"><span><strong>${sectors.length}</strong> gremios</span><span><strong>${sectors.length*3}</strong> diseños</span><span><strong>1</strong> blog motero</span></div></div></section><section id="catalogo" aria-label="Catálogo de diseños"><div class="catalog-tools"><label class="search"><span aria-hidden="true">⌕</span><input id="search" type="search" placeholder="¿Para qué negocio buscas una web?" aria-label="Buscar por gremio o servicio"></label><label><span class="skip">Filtrar por categoría</span><select id="category" aria-label="Filtrar por categoría"><option value="all">Todos los sectores</option>${categories.map(c=>`<option>${c}</option>`).join('')}</select></label><label class="toggle"><input id="ticket" type="checkbox">Solo ticket alto</label></div><div class="catalog-head"><p id="result-count" role="status" aria-live="polite">${sectors.length} gremios · ${sectors.length*3} diseños</p><a href="#especial">Descubre Motoyayos</a></div><div class="grid">${sectors.map(card).join('')}<div id="empty" class="empty" hidden><h3>No encontramos ese gremio.</h3><p>Prueba con otro nombre o cambia los filtros.</p><button class="btn secondary" id="reset">Ver todos los gremios</button></div></div><div class="catalog-pagination"><button id="show-more" class="btn secondary">Ver más gremios</button></div></section><section class="moto-banner" id="especial"><img src="/assets/motoyayos-logo.webp" width="1000" height="1000" loading="lazy" alt="Emblema Motoyay@s, con moto clásica y Valera de Abajo"><div><span class="eyebrow">Fuera del catálogo. Dentro de la carretera.</span><h2>Motoyayos</h2><p>Un cuaderno de rutas, encuentros y pequeños viajes sobre dos ruedas. Con personalidad propia y muchas historias por contar.</p></div>${btn('Entrar en el blog','/motoyayos/')}</section></main>${footer()}`));
for(const s of sectors){write(`sectores/${s.id}`,shell(`${s.name} · Tres diseños | Estudio Web`,`Compara tres versiones para ${s.name.toLowerCase()}: ${byId[s.id].versions.map(v=>v.name).join(", ")}.`,`${hubnav()}<main id="main" class="wrap"><div class="breadcrumb"><a href="/">Catálogo</a> / ${esc(s.name)}</div><section class="sector-intro"><span class="eyebrow">${esc(s.category)} ${s.highTicket?'· Ticket alto':''}</span><h1>${esc(s.name)}.<br>Tres formas de presentarte.</h1><p>Tres propuestas para explorar ${byId[s.id].features.map(x=>x.toLowerCase()).join(", ")}. Abre cada diseño y prueba el recorrido completo.</p></section><div class="grid">${byId[s.id].versions.map(v=>`<article class="preview"><a class="real-preview" href="/demos/${s.id}/${v.id}/"><img src="/assets/previews/${s.id}-${v.id}.webp" width="640" height="410" loading="lazy" alt="Vista real de ${esc(v.name)} para ${esc(s.name)}"></a><div class="preview-copy"><span class="eyebrow">VERSIÓN ${v.id.toString().padStart(2,'0')}</span><h3>${v.name}</h3><p>${v.description}. Interacciones completas y datos de ejemplo.</p>${btn('Explorar esta web',`/demos/${s.id}/${v.id}/`)}</div></article>`).join('')}</div><p style="margin:35px 0 60px;color:var(--muted)">Marca de ejemplo: ${esc(s.brand)}. Reservas y gestiones de prueba completas, con confirmación, descarga y cancelación en este navegador.</p></main>${footer()}`));
for(const v of variants)write(`demos/${s.id}/${v.id}`,renderDemo(s,v));}
const motonav=()=>`<header class="topbar"><nav class="nav wrap" aria-label="Navegación Motoyayos"><a class="wordmark" href="/motoyayos/"><img src="/assets/motoyayos-icon.webp" width="160" height="160" alt="">Motoyayos</a><div class="navlinks"><a href="/motoyayos/#historias">El blog</a><a href="/motoyayos/#nosotros">Quiénes somos</a><a class="optional" href="/">Catálogo</a></div></nav></header>`;
const motofooter=()=>`<footer class="site-footer wrap"><span>Motoyay@s · Valera de Abajo · Dos ruedas y muchas historias.</span><a href="/assets/motoyayos-logo.webp" download="motoyayos-logo.webp">Descargar logotipo WebP</a><a href="/">Catálogo de webs</a></footer>`;
const postcard=p=>`<article class="post-card" data-post="${p.category}"><a href="/motoyayos/blog/${p.id}/">${photo(p.photo,p.title)}<div class="post-meta">${p.category} · ${p.read}</div><h3>${p.title}</h3><p>${p.intro}</p><span style="font-size:.85rem;text-decoration:underline">Leer historia</span></a></article>`;
write('motoyayos',shell('Motoyayos · Rutas, motos e historias','El blog de Motoyay@s, Valera de Abajo. Rutas, consejos y crónicas para disfrutar de las dos ruedas.',`${motonav()}<main id="main" class="wrap"><section class="moto-intro"><div><span class="eyebrow">Valera de Abajo · Cuaderno de carretera</span><h1>No contamos años.<br>Contamos <em>kilómetros.</em></h1><p>Rutas sin prisa, cafés en buena compañía y esas historias que solo pasan cuando sales a rodar.</p><div class="biz-actions">${btn('Leer el blog','#historias')}${btn('Conocer Motoyayos','#nosotros','secondary')}</div></div><img src="/assets/motoyayos-logo.webp" width="1000" height="1000" fetchpriority="high" alt="Logotipo Motoyay@s, Valera de Abajo, moto clásica ante un paisaje"></section><section class="moto-feature">${photo(8,'Motorista en una carretera entre montañas')}<div><span class="eyebrow">La ruta de la semana · Artículo de ejemplo</span><h2>El camino también es el destino.</h2><p>Una mañana por la Serranía, una parada con vistas y ninguna prisa por volver.</p><a href="/motoyayos/blog/una-manana-por-la-serrania/">Leer la ruta</a></div></section><section id="historias"><div class="section-top"><div><span class="eyebrow">El cuaderno</span><h2 style="font-family:var(--serif)">Historias entre curvas.</h2></div><p>Primeras entradas de muestra. Un espacio listo para las rutas y las fotografías de su autor.</p></div><div class="pills" aria-label="Filtrar artículos">${['Todas','Rutas','Consejos','Crónicas'].map((c,i)=>`<button data-filter="${c}" aria-pressed="${i===0}">${c}</button>`).join('')}</div><div class="grid">${posts.map(postcard).join('')}</div></section><section class="about-moto" id="nosotros"><div><span class="eyebrow">Más que un nombre</span><h2>La carretera se disfruta.<br>Las historias se comparten.</h2></div><div><p>Motoyayos es una propuesta de blog para un motero con ganas de guardar y compartir sus rutas. Su emblema nace del llavero de Motoyay@s, Valera de Abajo: una moto clásica, un paisaje y unas raíces.</p><p>Aquí caben las escapadas de fin de semana, los consejos aprendidos con el tiempo y los encuentros que merecen una foto. El propietario pondrá su voz y sus experiencias reales en este cuaderno.</p><a href="/motoyayos/blog/por-que-un-blog-motero/" style="text-decoration:underline">La idea detrás del blog</a></div></section></main>${motofooter()}`,'moto'));
posts.forEach((p,i)=>{const next=posts[(i+1)%posts.length];write(`motoyayos/blog/${p.id}`,shell(`${p.title} | Motoyayos`,p.intro,`${motonav()}<main id="main"><article class="article"><div class="breadcrumb"><a href="/motoyayos/#historias">El blog</a> / ${p.category}</div><p class="post-meta">${p.category} · ${p.date} · ${p.read} de lectura</p><h1>${p.title}</h1><p class="lead">${p.intro}</p>${photo(p.photo,p.title)}${p.sections.map(([h,t])=>`<h2>${h}</h2><p>${t}</p>`).join('')}<p class="sample">Artículo de demostración. Texto e imagen preparados para presentar el blog; no documentan un viaje real de su propietario. Antes de seguir una ruta, comprueba siempre las condiciones actuales.</p><div class="read-next"><span class="eyebrow">Sigue leyendo</span><h3><a href="/motoyayos/blog/${next.id}/">${next.title}</a></h3>${btn('Volver a las historias','/motoyayos/#historias','secondary')}</div></article></main>${motofooter()}`,'moto'))});
fs.writeFileSync(root+'/404.html',shell('Página no encontrada | Estudio Web','Vuelve al catálogo para encontrar tu diseño.',`${hubnav()}<main id="main" class="wrap" style="padding-top:80px;padding-bottom:100px"><span class="eyebrow">404</span><h1>Esta dirección<br>no está en el catálogo.</h1><p>Explora los gremios o entra en el blog de Motoyayos.</p>${btn('Volver al catálogo','/')}</main>${footer()}`));
fs.writeFileSync(root+'/robots.txt','User-agent: *\nAllow: /\nSitemap: https://gpt2026.vercel.app/sitemap.xml\n');
fs.writeFileSync(root+'/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p=>`<url><loc>https://gpt2026.vercel.app${p}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync(root+'/assets/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="13" fill="#192c32"/><path d="M17 20h28v7H25v5h17v7H25v5h20v7H17z" fill="#f4f5f1"/></svg>');
console.log(`Built ${pages.length} pages: ${sectors.length} sectors, ${sectors.length*3} demos, Motoyayos and ${posts.length} articles.`);
