import * as pdfjs from './vendor/pdf.min.mjs';
pdfjs.GlobalWorkerOptions.workerSrc='/assets/ocrtrabajo/vendor/pdf.worker.min.mjs';
const $=s=>document.querySelector(s), storageKey='ocrtrabajo-template-v1';
const defaults=[['nombre','Nombre','dni','Nombre'],['apellidos','Apellidos','dni','Apellidos'],['documento','DNI / NIE','dni',''],['domicilio','Domicilio','dni','Domicilio'],['pedido','Número de pedido','pedido','Número de pedido'],['fecha','Fecha del pedido','pedido','Fecha'],['matricula','Matrícula','pedido','Matrícula'],['vehiculo','Vehículo','pedido','Vehículo'],['importe','Importe','pedido','Total'],['telefono','Teléfono','pedido','Teléfono'],['email','Correo electrónico','pedido','Email']].map(([id,title,doc,label])=>({id,title,doc,label}));
let config={sources:defaults,mappings:{}},capture=null,values={},busy=false;
try{const raw=localStorage.getItem(storageKey);if(raw)config=validate(JSON.parse(raw));}catch{}
function validate(x){if(!x||!Array.isArray(x.sources)||x.sources.length>100||!x.mappings||typeof x.mappings!=='object')throw Error('Configuración no válida.');for(const s of x.sources)if(!s||!['pedido','dni'].includes(s.doc)||['id','title','label'].some(k=>typeof s[k]!=='string'||s[k].length>180))throw Error('Dato no válido.');if(new Set(x.sources.map(s=>s.id)).size!==x.sources.length)throw Error('Identificadores duplicados.');return {sources:x.sources.map(({id,title,doc,label})=>({id,title,doc,label})),mappings:x.mappings};}
function el(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;}
function input(value,onChange){const e=el('input');e.value=value||'';e.addEventListener('input',()=>onChange(e.value));return e;}
function select(options,value,onChange){const e=el('select');for(const [v,t]of options){const o=el('option',t);o.value=v;e.append(o);}e.value=value||'';e.onchange=()=>onChange(e.value);return e;}
function cell(row,child){const td=el('td');td.append(child);row.append(td);}
function renderSources(){const body=$('#sources');body.replaceChildren();for(const s of config.sources){const row=el('tr');cell(row,input(s.title,v=>{s.title=v;}));cell(row,select([['dni','DNI'],['pedido','Pedido']],s.doc,v=>s.doc=v));cell(row,input(s.label,v=>s.label=v));cell(row,input(values[s.id],v=>values[s.id]=v));const remove=el('button','×');remove.className='secondary remove';remove.setAttribute('aria-label','Eliminar '+s.title);remove.onclick=()=>{config.sources=config.sources.filter(x=>x!==s);delete values[s.id];renderSources();renderMapping();};cell(row,remove);body.append(row);}}
function key(s,f){return JSON.stringify([s.section,f.selector||f.label]);}
function renderMapping(){const box=$('#mapping');box.replaceChildren();if(!capture){box.append(el('p','Importa los campos del expediente para configurar las asignaciones.'));return;}
 for(const s of capture.sections){const heading=el('h3',s.section);heading.className='section-title';box.append(heading);const wrap=el('div');wrap.className='table-wrap';const table=el('table');const head=el('tr');for(const text of ['Rellenar','Campo de la intranet','Dato de origen'])head.append(el('th',text));table.append(head);
 for(const f of s.fields){const k=key(s,f);const m=config.mappings[k]||{enabled:false,source:'',fixed:''};config.mappings[k]=m;const row=el('tr');const check=el('input');check.type='checkbox';check.checked=m.enabled;check.disabled=!f.selector;check.setAttribute('aria-label','Rellenar '+f.label);check.onchange=()=>m.enabled=check.checked;cell(row,check);const label=el('div',f.label+(f.required?' *':''));if(!f.selector){const warning=el('p','Sin identificador estable: requiere adaptación.');warning.className='field-warning';label.append(warning);}cell(row,label);
 const options=[['','Selecciona un dato'],...config.sources.map(x=>[x.id,x.title+' · '+(x.doc==='dni'?'DNI':'Pedido')])];if(f.options)options.push(['@fixed','Opción fija']);const group=el('div');const choose=select(options,m.source,v=>{m.source=v;renderMapping();});choose.setAttribute('aria-label','Dato para '+f.label);group.append(choose);
 if(m.source==='@fixed'&&f.options)group.append(select([['','Selecciona una opción'],...f.options.filter(o=>!o.disabled&&o.value).map(o=>[o.value,o.label])],m.fixed,v=>m.fixed=v));
 cell(row,group);table.append(row);}wrap.append(table);box.append(wrap);}}
function bridge(action,items){return new Promise((resolve,reject)=>{const id=crypto.randomUUID();const listener=e=>{if(e.source!==window||e.origin!==location.origin||e.data?.source!=='ocrtrabajo-extension'||e.data.id!==id)return;clearTimeout(timer);window.removeEventListener('message',listener);if(e.data.result?.error)reject(Error(e.data.result.error));else resolve(e.data.result);};const timer=setTimeout(()=>{window.removeEventListener('message',listener);reject(Error('No se ha podido conectar con la extensión. Instálala y recarga esta página.'));},action==='fill'?180000:5000);window.addEventListener('message',listener);window.postMessage({source:'ocrtrabajo-page',id,action,items},location.origin);});}
$('#import').onclick=async()=>{try{capture=await bridge('getScan');$('#capture-status').textContent=capture.sections.reduce((n,s)=>n+s.fields.length,0)+' campos reconocidos en '+capture.sections.length+' secciones.';renderMapping();}catch(e){$('#capture-status').textContent=e.message;}};
$('#add-source').onclick=()=>{config.sources.push({id:crypto.randomUUID(),title:'Nuevo dato',doc:'pedido',label:''});renderSources();renderMapping();};
function extract(){values={};for(const s of config.sources){const text=$('#'+s.doc+'-text').value;if(s.id==='documento'){values[s.id]=(text.toUpperCase().match(/\b(?:\d{8}[A-Z]|[XYZ]\d{7}[A-Z])\b/)||[])[0]||'';continue;}if(!s.label.trim())continue;const lines=text.split('\n');const at=lines.findIndex(line=>line.toLocaleLowerCase('es').includes(s.label.toLocaleLowerCase('es')));if(at<0)continue;const line=lines[at];const pos=line.toLocaleLowerCase('es').indexOf(s.label.toLocaleLowerCase('es'));values[s.id]=line.slice(pos+s.label.length).replace(/^\s*[:=\-]?\s*/,'').trim()||lines[at+1]?.trim()||'';}renderSources();}
$('#extract').onclick=extract;
async function imageOCR(file,worker){const bitmap=await createImageBitmap(file);try{const canvas=document.createElement('canvas');const scale=Math.min(1,3000/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);return (await worker.recognize(canvas)).data.text;}finally{bitmap.close();}}
async function readPDF(file,worker){const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false,cMapUrl:"/assets/ocrtrabajo/vendor/cmaps/",cMapPacked:true,standardFontDataUrl:"/assets/ocrtrabajo/vendor/standard_fonts/"}).promise;try{let text='';if(pdf.numPages>50)throw Error('El PDF supera 50 páginas. Divide el documento.');for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n);const content=await page.getTextContent();const embedded=content.items.map(i=>i.str+(i.hasEOL?'\n':' ')).join('');$('#status').textContent='Leyendo PDF · página '+n+' de '+pdf.numPages;if(embedded.trim().length>30)text+=embedded+'\n';else{const base=page.getViewport({scale:1});const view=page.getViewport({scale:Math.min(2,3000/Math.max(base.width,base.height))});const canvas=document.createElement('canvas');canvas.width=Math.ceil(view.width);canvas.height=Math.ceil(view.height);await page.render({canvasContext:canvas.getContext('2d'),viewport:view}).promise;text+=(await worker.recognize(canvas)).data.text+'\n';}page.cleanup();}return text;}finally{await pdf.destroy();}}
$('#process').onclick=async()=>{if(busy)return;const docs=['pedido','dni'].flatMap(doc=>[...$('#'+doc).files].map(file=>({doc,file})));if(!docs.length){$('#status').textContent='Selecciona un pedido o un DNI.';return;}if(docs.some(({file})=>file.size>30*1024*1024)){ $('#status').textContent='Cada archivo debe ocupar menos de 30 MB.';return;}
 busy=true;$('#status').textContent='Preparando el OCR local…';$('#process').disabled=true;$('#clear').disabled=true;$('#fill').disabled=true;$('#progress').hidden=false;$('#pedido-text').value='';$('#dni-text').value='';values={};renderSources();let worker;
 try{worker=await Tesseract.createWorker('spa',1,{workerPath:'/assets/ocrtrabajo/vendor/worker.min.js',corePath:'/assets/ocrtrabajo/vendor/core',langPath:'/assets/ocr-models',gzip:false,cacheMethod:'none',workerBlobURL:false,logger:m=>{if(m.status==='recognizing text'){$('#progress').value=m.progress;}}});for(const {doc,file}of docs){$('#status').textContent='Leyendo '+file.name;const text=file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')?await readPDF(file,worker):await imageOCR(file,worker);$('#'+doc+'-text').value+=text+'\n';}extract();$('#status').textContent='Lectura terminada. Revisa los datos extraídos, especialmente el DNI y los importes.';}catch(e){$('#status').textContent='No se pudo completar la lectura: '+e.message;}finally{if(worker)await worker.terminate();busy=false;$('#process').disabled=false;$('#clear').disabled=false;$('#fill').disabled=false;$('#progress').hidden=true;}};
$('#clear').onclick=()=>{for(const doc of ['pedido','dni']){$('#'+doc).value='';$('#'+doc+'-text').value='';}values={};renderSources();$('#status').textContent='Documentos y datos borrados de esta página.';$('#fill-status').textContent='';};
$('#save').onclick=()=>{try{localStorage.setItem(storageKey,JSON.stringify(config));$('#fill-status').textContent='Configuración guardada en este navegador. No se han guardado los documentos ni sus valores.';}catch{$('#fill-status').textContent='El navegador no permite guardar la configuración.';}};
$('#export-config').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(config,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download='ocrtrabajo-config.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#config-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1024*1024)throw Error('Configuración demasiado grande.');config=validate(JSON.parse(await file.text()));values={};renderSources();renderMapping();$('#fill-status').textContent='Configuración importada. Pulsa Guardar para conservarla.';}catch(err){$('#fill-status').textContent=err.message;}e.target.value='';};
$('#fill').onclick=async()=>{try{if(!capture)throw Error('Importa primero los campos del expediente.');const items=[];for(const s of capture.sections)for(const f of s.fields){const m=config.mappings[key(s,f)];if(!m?.enabled||!f.selector)continue;let value=m.source==='@fixed'?m.fixed:values[m.source];if(!value?.trim())continue;if(f.options&&m.source!=='@fixed'){const match=f.options.find(o=>!o.disabled&&(o.value===value||o.label.toLocaleLowerCase('es')===value.toLocaleLowerCase('es')));if(!match)throw Error('Selecciona una opción fija para «'+f.label+'»: no hay una coincidencia exacta.');value=match.value;}items.push({selector:f.selector,tabSelector:s.tabSelector,label:f.label,value});}if(!items.length)throw Error('Marca campos, asigna datos y revisa sus valores.');$('#fill').disabled=true;$('#fill-status').textContent='Confirma el rellenado en la pestaña de la intranet.';const result=await bridge('fill',items);$('#fill-status').textContent=result.cancelled?'Rellenado cancelado.':result.count+' campos rellenados. '+(result.errors.length?result.errors.join(' · '):'Revisa el expediente y guárdalo en la intranet.');}catch(e){$('#fill-status').textContent=e.message;}finally{$('#fill').disabled=false;}};
renderSources();renderMapping();
