export const posts=[
{id:'una-manana-por-la-serrania',category:'Rutas',title:'Una mañana por la Serranía: curvas y una buena parada',intro:'Hay rutas que no necesitan muchos kilómetros. Solo una carretera tranquila, tiempo para mirar y ganas de disfrutar del camino.',date:'2 octubre 2026',read:'4 min',photo:8,sections:[
['Salir con margen','La mejor parte de una salida corta es que no exige una gran preparación. Elegir una mañana sin prisas permite revisar la moto, mirar la previsión y decidir cuánto tiempo queremos dedicar a cada parada. El objetivo no tiene por qué ser llegar lejos: a veces basta con salir de la carretera de siempre y descubrir un desvío conocido con otra luz.'],
['Una ruta flexible','Una propuesta para una primera crónica podría partir de Valera de Abajo y explorar el entorno de la Serranía de Cuenca. Antes de convertirla en un itinerario concreto conviene comprobar el estado de las carreteras, los accesos y las condiciones del día. No publicamos un trazado cerrado ni tiempos garantizados: el recorrido debe ajustarse a la experiencia del grupo, la meteorología y las paradas que realmente apetezcan.'],
['Parar también es viajar','Un mirador, un café o una conversación pueden dar sentido a la salida. Elige lugares donde aparcar sin obstaculizar el paso y deja las fotografías para cuando la moto esté detenida. Si vamos acompañados, acordar de antemano puntos de encuentro evita que nadie sienta la necesidad de recuperar terreno.'],
['Lo que merece una crónica','Al volver, guarda tres cosas: una imagen del paisaje, una nota sobre la parada favorita y una pequeña anécdota. Con eso puede empezar un buen artículo. Una ruta personal se recuerda por lo que nos hizo sentir, y esas sensaciones son las que dan vida a un blog motero.']
]},
{id:'equipaje-para-una-escapada',category:'Consejos',title:'Menos equipaje, más carretera',intro:'Una escapada de fin de semana empieza mejor cuando todo tiene su sitio. Una lista sencilla para organizarse sin llevar media casa.',date:'1 octubre 2026',read:'3 min',photo:8,sections:[
['Pensar en días, no en posibilidades','La tentación de cargar por si acaso puede llenar las maletas antes de salir. Empieza por la duración real del viaje, la previsión meteorológica y la posibilidad de encontrar servicios en el camino. Separa lo imprescindible de lo que simplemente resulta cómodo. Una lista escrita evita duplicados y permite revisar con calma.'],
['Repartir el peso','Respeta siempre los límites de carga de la moto y del sistema de equipaje indicados por sus fabricantes. Asegura cada pieza y comprueba que no interfiera con el escape, la dirección o las ruedas. El reparto del peso debe mantener la moto equilibrada; si tienes dudas, consulta el manual o pide orientación a un taller.'],
['Lo que debe quedar a mano','Documentación, agua, protección frente a la lluvia y los objetos necesarios en una parada pueden ir en un compartimento accesible. Guarda los objetos sensibles al agua en fundas adecuadas. Evita depender exclusivamente del teléfono para todas las gestiones: una copia accesible de la información básica puede resultar útil.'],
['Una comprobación antes de rodar','Dedica unos minutos a revisar cierres, anclajes y holguras con la moto parada. Si es la primera vez que utilizas ese equipaje, haz una prueba corta en un entorno adecuado antes del viaje. Al final, la mejor maleta es la que permite olvidarse de ella y concentrarse en conducir.']
]},
{id:'el-cafe-de-la-primera-parada',category:'Crónicas',title:'El café de la primera parada',intro:'La excusa era salir en moto. Lo que de verdad apetecía era encontrarnos, hablar un rato y compartir la mañana.',date:'28 septiembre 2026',read:'3 min',photo:1,sections:[
['La salida como punto de encuentro','Este es un ejemplo de la clase de crónica que puede tener Motoyayos: una historia pequeña, cercana y sin necesidad de convertir cada salida en una hazaña. El punto de partida es sencillo. Varias personas acuerdan una mañana libre, un lugar de encuentro y un recorrido que deja espacio para parar.'],
['Cada uno a su ritmo','Un buen grupo entiende que disfrutar no significa rodar todos de la misma manera. Acordar quién abre, dónde reagruparse y cómo avisar de una parada ayuda a que la salida sea cómoda. Nadie debería sentirse obligado a seguir un ritmo que no le encaja. La conversación continúa en el siguiente punto de encuentro.'],
['Una mesa y muchas historias','Las mejores conversaciones no suelen necesitar un tema preparado. Aparecen recuerdos de motos anteriores, planes de viaje y recomendaciones que alguien apunta en el móvil. Un café se alarga porque lo que importa no es tachar kilómetros, sino compartir tiempo con personas que disfrutan de lo mismo.'],
['Volver con algo que contar','Una foto del grupo con su permiso, el nombre de la parada y unas líneas sobre el día bastan para empezar. El blog puede guardar esos momentos para quien estuvo allí y para quien se sumará a la siguiente salida. Esta crónica de muestra está pensada para que su autor la sustituya por una experiencia propia.']
]},
{id:'revisar-la-moto-antes-de-salir',category:'Consejos',title:'Cinco minutos antes de salir',intro:'Una revisión sencilla, con la moto detenida, ayuda a empezar una ruta con más tranquilidad.',date:'25 septiembre 2026',read:'3 min',photo:8,sections:[
['El manual manda','Cada moto tiene sus propias especificaciones. La presión de los neumáticos, los intervalos de mantenimiento y el modo de comprobar los niveles deben consultarse en el manual. Una lista general sirve para recordar qué revisar, pero no sustituye las instrucciones del fabricante ni una inspección profesional.'],
['Una mirada alrededor','Comprueba visualmente el estado de los neumáticos, busca fugas y verifica que no haya objetos o piezas sueltas. Revisa luces e intermitentes con la moto detenida. Si algo parece distinto de lo habitual, es mejor resolverlo antes de salir que esperar a descubrir la causa en la carretera.'],
['Preparar también al motorista','La ruta depende de cómo se encuentra quien conduce. Descanso, hidratación, equipamiento adecuado y una previsión razonable son parte de la preparación. Evita salir con prisas y deja margen para ajustar el plan si cambia el tiempo. Un itinerario siempre puede esperar.'],
['Cuando hay dudas','Ruidos nuevos, una frenada extraña o una pérdida de presión merecen atención profesional. Esta entrada ofrece recordatorios generales, no instrucciones de reparación. El blog puede enlazar en el futuro los recursos oficiales del modelo de moto y las recomendaciones del taller de confianza de su autor.']
]},
{id:'planear-una-ruta-sin-prisas',category:'Rutas',title:'Cómo elegir una ruta para disfrutar sin prisas',intro:'No siempre gana la ruta más larga. A veces el mejor recorrido es el que deja sitio para cambiar de plan.',date:'22 septiembre 2026',read:'4 min',photo:8,sections:[
['Empezar por el tiempo disponible','Antes de buscar carreteras, decide cuándo quieres estar de vuelta. Reserva margen para repostar, descansar y hacer una parada imprevista. Si la salida es en grupo, ten en cuenta la autonomía y la experiencia de todas las personas. Una ruta que encaja en la mañana suele disfrutarse más que una agenda que obliga a correr.'],
['Comprobar el recorrido','Contrasta el itinerario con información actualizada sobre tráfico, meteorología y posibles cortes. Un mapa puede sugerir una carretera bonita, pero no describe necesariamente su estado hoy. Identifica alternativas y puntos donde puedas acortar la ruta si las condiciones cambian.'],
['Elegir buenas paradas','La distancia entre paradas debe ajustarse al grupo y al cansancio. Busca lugares donde detenerse de forma segura, beber agua y estirar un poco. Un mirador o un pueblo con una plaza agradable pueden ser el centro del plan en lugar de una simple interrupción.'],
['Guardar la experiencia','Después de la salida, anota qué funcionó y qué cambiarías. Al publicar una ruta real en Motoyayos se pueden añadir el recorrido verificado, las fotografías propias y la fecha en que se hizo. Así los lectores podrán distinguir una experiencia personal de una recomendación general.']
]},
{id:'por-que-un-blog-motero',category:'Crónicas',title:'Un cuaderno para las cosas que pasan entre curvas',intro:'Una web propia puede guardar lo que una publicación rápida deja atrás: las historias, las rutas y las personas.',date:'20 septiembre 2026',read:'3 min',photo:8,sections:[
['Una casa para las historias','Motoyayos nace aquí como propuesta de blog personal. Un espacio donde cada salida pueda convertirse en algo más que unas fotos dispersas: una entrada con contexto, una ruta que volver a consultar y un recuerdo que siga siendo fácil de encontrar con el paso del tiempo.'],
['La voz del autor','No hace falta escribir como una revista. Un tono cercano, una anécdota honesta y una fotografía propia suelen contar más que un texto perfecto. El autor puede hablar de lo que le gusta de su moto, de una carretera que siempre vuelve a recorrer o de una persona que conoció en una parada.'],
['Un emblema con raíces','El llavero que inspira esta web reúne una moto clásica y el nombre de Valera de Abajo. La recreación del logotipo conserva ese espíritu de pertenencia y carretera. El emblema funciona como firma del blog y como un punto de conexión entre las entradas, las rutas y los encuentros.'],
['El siguiente capítulo','Estas primeras entradas son ejemplos para mostrar cómo podría funcionar el blog. El siguiente paso será incorporar fotografías y relatos del propietario, ajustar su presentación y decidir qué quiere compartir. El diseño ya deja espacio para crecer sin que publicar una nueva historia cambie la identidad del sitio.']
]}
];
